### ISSUE TITLE
A few issues with the latest update RNRC (20/4/16)

### ISSUE THREAD

**Issue by SCHNZP** [Esri/crime-analysis-toolbox#75]
Running the latest RNRC version on the Naperville dataset, listing all these issues here as they may be different symptoms of the same issue.

1. Output volumes and percentage add to more than the sample size, more than 100% (suspect maybe it's counting connections rather than points since we now have a lot more connections??):
![image](https://cloud.githubusercontent.com/assets/18314779/14727204/db36374a-087c-11e6-8312-eede0807776f.png)
![image](https://cloud.githubusercontent.com/assets/18314779/14727206/dd299650-087c-11e6-9a95-701e0f078097.png)

2. In this pair here, the O has been given the space and time bands, and distance-to-originator, whereas I think those attributes belong to the NR (which doesn't have the bands but does have the distance):
![image](https://cloud.githubusercontent.com/assets/18314779/14727222/0b98b7dc-087d-11e6-82c1-fe5b7ecfb5c5.png)

3. A lot of the NRs have NULL space and time bands (yet have distance-to-originator):
![image](https://cloud.githubusercontent.com/assets/18314779/14727246/3e3692ea-087d-11e6-8b21-ab9b12ecd484.png)

A general comment on the new connections which connect everything to everything within an NR cluster/chain - this is definitely more informative, a more complete visualisation. Would still like the option of generating a connections layer which only includes connections between the latest/most recent originator to see potential series evolution in time sequence.

**Comment by SCHNZP** [comment]
Another potentially relevant observation: The Results screen says there were 432 incidents yet there are 541 features in the attribute table.

**Comment by allisonmuise** [comment]
Thanks @SCHNZP : Could you hold off testing this tool for a few more days? I've been out of the office and I'm just catching back up. We aren't quite done with the updates based on your earlier observations.

**Comment by allisonmuise** [comment]
> The Results screen says there were 432 incidents yet there are 541 features in the attribute table.

@SCHNZP Please confirm that the tool is now reporting the correct number of incidents

>Would still like the option of generating a connections layer which only includes connections between the latest/most recent originator to see potential series evolution in time sequence.

We'll come back to this in a future release of the tools. For now you could use ModelBuilder to select each of the O features, use Select By Location to select all features within a distance of the O, and then use POint to Line to create a line feature that connects all the pts in order of date.

>A lot of the NRs have NULL space and time bands (yet have distance-to-originator):

Addressed in another issue - band values cannot be calculated as an incident may fall into several different bands relative to many features. If you delete these fields they should not be re-generated.

>In this pair here, the O has been given the space and time bands, and distance-to-originator, whereas I think those attributes belong to the NR (which doesn't have the bands but does have the distance):

As above. I suspect that those O features were formerly NRs adn they now appear to have bands because those fields were not cleared.

>Output volumes and percentage add to more than the sample size, more than 100% (suspect maybe it's counting connections rather than points since we now have a lot more connections??):

Please confirm that this is not an issue in the latest version of the tool.

**Comment by SCHNZP** [comment]
I reran it now with the output fields cleared from the dataset first. Still appears to be adding to more than 100%. The overall count and % seems right (49% NRs, 18% Rs, 100% all incidents) but the breakdown table by time and distance bands says 22% Rs within 21 days and 123% NRs within 21 days and max distance band 1500ft.
![image](https://cloud.githubusercontent.com/assets/18314779/15061410/35377abc-1389-11e6-80e8-69b8ab1b72d2.png)
![image](https://cloud.githubusercontent.com/assets/18314779/15061412/3937782e-1389-11e6-98ec-d474ed866e0d.png)

**Comment by allisonmuise** [comment]
@SCHNZP : Could you try again with the latest code? This was an issue a few days ago, but should be fixed in the current tool

**Comment by SCHNZP** [comment]
Now this is odd: I changed that dataset from a featureclass to a shpfile before running the new tool on it. With the latest code and using each of the 3 date fields in that dataset it now produces the NOT NULLABLE error. I have sent you through the dataset by email. Then I ran the RNRC on the featureclass version and it has worked - no error!

**Comment by SCHNZP** [comment]
oops that comment was supposed to be under issue 81. Have updated. 

Re the %ages - appears fixed in latest code. Naperville table now says total 39.4 withn 21 days 1500ft in the table. Though the summary table with the overall number of offences, Rs and NRs has gone?

**Comment by allisonmuise** [comment]
@SCHNZP : Yes, that was deliberate. These counts would not each require a table per space/time band combo which made the report quite large, and the numbers can be easily discovered from the data.
